# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "t3d-app"
client_id = "38131c5c7410151c7de5e289b1e28871"
application_url = "https://the-third-dimension.xyz"
embedded = true
handle = "t3d-app"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "bsbunj-hc.myshopify.com"

[webhooks]
api_version = "2024-01"

[access_scopes]
# Use access scopes to specify the level of access your app needs
scopes = "write_products,write_customers,write_draft_orders"

[auth]
redirect_urls = [
    "https://the-third-dimension.xyz/auth/callback",
]

[pos]
embedded = false

[deployment]
deployment_method = "oxygen"
